### ISSUE TITLE
redis.exceptions.ResponseError: unknown command `BF.RESERVE`, with args beginning with: `bloom`, `0.01`, `1000`

### ISSUE THREAD

**Issue by phpsxg** [RedisBloom/redisbloom-py#23]
rb = Client(host=custom_config.QINGSHIHE_HOST, port=custom_config.REDIS_PORT)
rb.bfCreate('bloom', 0.01, 1000)

fail:
**redis.exceptions.ResponseError: unknown command `BF.RESERVE`, with args beginning with: `bloom`, `0.01`, `1000`**

**Comment by gkorland** [comment]
@phpsxg how did you start the server? which version of the module are you using?

**Comment by amanAtHoneyHealth** [comment]
Having the same issue with version 7.0.10. And also started the server
