### ISSUE TITLE
Support redis-py 4.1.0

### ISSUE THREAD

**Issue by kylekyle** [RedisBloom/redisbloom-py#46]
It would be useful to use CMS in cluster-mode to count very large sets. That is only supported in redis-py 4.1.0 or greater.

**Comment by gkorland** [comment]
Please notice this client is deprecated all the module API were added to redis-py.
See: https://redis-py.readthedocs.io/en/stable/redismodules.html#redisbloom-commands

**Comment by kylekyle** [comment]
Great! redis-py seems to work. Unfortunately, they don't support using modules in cluster mode yet. Either way, it's not an issue here. Thanks!
